# -*- coding: utf-8 -*-
"""Assignment-8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LzqicnYNu-6UjykStXdWeBn0LInfyN4o
"""

import numpy as np
import matplotlib.pyplot as plt
 
#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB
 
#Plotting line x+y = 4
A=np.array([4,0])
B=np.array([0,4])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='x+y=4')
 
#Plotting line 2x-y=0
P=np.array([4,8])
Q=np.array([0,0])
PQ=line_gen(P,Q)
plt.plot(PQ[0,:],PQ[1,:],label='2x-y=0')
 
#Shading Required Region
x1=[4,0,4/3,8/3]
y1=[0,0,8/3,4/3]
plt.fill(x1,y1,color='blue',alpha=0.3)
 
 
#Labelling points
plt.plot(0,4,'o',color='r')
plt.text(0,4,'A(0,4)')
plt.plot(4/3,8/3,'o',color='r')
plt.text(1.3,2.6,'O(4/3,8/3)')
plt.plot(4,0,'o',color='r')
plt.text(4,0,'B(4,0)')
plt.plot(4,8,'o',color='r')
plt.text(4,8,'C(4,8)')
plt.plot(0,0,'o',color='r')
plt.text(0,0,'D(0,0)')
 
plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()